# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UIviews\Uiapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 802)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_main = QtWidgets.QWidget(self.centralwidget)
        self.widget_main.setObjectName("widget_main")
        self.THEAPPLICATIONCHILD = QtWidgets.QVBoxLayout(self.widget_main)
        self.THEAPPLICATIONCHILD.setContentsMargins(0, 0, 0, 0)
        self.THEAPPLICATIONCHILD.setSpacing(0)
        self.THEAPPLICATIONCHILD.setObjectName("THEAPPLICATIONCHILD")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalFrame_panal = QtWidgets.QFrame(self.widget_main)
        self.verticalFrame_panal.setMinimumSize(QtCore.QSize(250, 0))
        self.verticalFrame_panal.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verticalFrame_panal.setStyleSheet("QFrame{\n"
"\n"
"background-color :rgb(35,35,35);\n"
"font: 8.5pt \"Segoe UI\";\n"    #garage manager font size
"}\n"
"")
        self.verticalFrame_panal.setObjectName("verticalFrame_panal")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame_panal)
        self.verticalLayout_5.setContentsMargins(0, 12, 0, 17)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logo = QtWidgets.QPushButton(self.verticalFrame_panal)
        self.logo.setMinimumSize(QtCore.QSize(40, 40))
        self.logo.setMaximumSize(QtCore.QSize(40, 40))
        self.logo.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
" }")
        self.logo.setText("")
        self.logo.setIcon(icon)
        self.logo.setIconSize(QtCore.QSize(40, 40))
        self.logo.setObjectName("logo")
        self.verticalLayout_5.addWidget(self.logo, 0, QtCore.Qt.AlignHCenter)
        self.appname = QtWidgets.QLabel(self.verticalFrame_panal)
        self.appname.setStyleSheet("color : #858585 ;")
        self.appname.setText("")
        self.appname.setAlignment(QtCore.Qt.AlignCenter)
        self.appname.setObjectName("appname")
        self.verticalLayout_5.addWidget(self.appname)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.adduser = QtWidgets.QRadioButton(self.verticalFrame_panal)
        self.adduser.setMinimumSize(QtCore.QSize(250, 50))
        self.adduser.setMaximumSize(QtCore.QSize(250, 50))
        self.adduser.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.adduser.setStyleSheet("QRadioButton{ \n"
"background-color :  transparent;\n"
"border : none ;\n"
"Text-align:right;\n"
"padding-right : 15px;\n"
"color : #858585;\n"
" }\n"
"\n"
"QRadioButton:hover{\n"
"background-color: rgb( 45, 45, 45);\n"
"\n"
"}\n"
"QRadioButton:checked{\n"
"background-color : rgb( 45, 45, 45); ;\n"
"border-bottom: 0px;\n"
"border-top: 0px;\n"
"border-left: 0px;\n"
"border-right: 3px  solid rgb( 174, 243, 231 );\n"
"padding-right: 12px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"                            width:                  0px;\n"
"                            height:                 0px;\n"
"                            border-radius:          0px;\n"
" }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/essential/add-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adduser.setIcon(icon1)
        self.adduser.setIconSize(QtCore.QSize(20, 20))
        self.adduser.setChecked(True)
        self.adduser.setObjectName("adduser")
        self.verticalLayout_5.addWidget(self.adduser)
        self.users = QtWidgets.QRadioButton(self.verticalFrame_panal)
        self.users.setMinimumSize(QtCore.QSize(250, 50))
        self.users.setMaximumSize(QtCore.QSize(250, 50))
        self.users.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.users.setStyleSheet("QRadioButton{ \n"
"background-color :  transparent;\n"
"border : none ;\n"
"Text-align:right;\n"
"padding-right : 15px;\n"
"color : #858585;\n"
" }\n"
"\n"
"QRadioButton:hover{\n"
"background-color: rgb( 45, 45, 45);\n"
"\n"
"}\n"
"QRadioButton:checked{\n"
"background-color : rgb( 45, 45, 45); ;\n"
"border-bottom: 0px;\n"
"border-top: 0px;\n"
"border-left: 0px;\n"
"border-right: 3px  solid rgb( 174, 243, 231 );\n"
"padding-right: 12px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"                            width:                  0px;\n"
"                            height:                 0px;\n"
"                            border-radius:          0px;\n"
" }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/core/user-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.users.setIcon(icon2)
        self.users.setIconSize(QtCore.QSize(20, 20))
        self.users.setObjectName("users")
        self.verticalLayout_5.addWidget(self.users)
        self.sendsms = QtWidgets.QRadioButton(self.verticalFrame_panal)
        self.sendsms.setMinimumSize(QtCore.QSize(250, 50))
        self.sendsms.setMaximumSize(QtCore.QSize(250, 50))
        self.sendsms.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sendsms.setStyleSheet("QRadioButton{ \n"
"background-color :  transparent;\n"
"border : none ;\n"
"Text-align:right;\n"
"padding-right : 15px;\n"
"color : #858585;\n"
" }\n"
"\n"
"QRadioButton:hover{\n"
"background-color: rgb( 45, 45, 45);\n"
"\n"
"}\n"
"QRadioButton:checked{\n"
"background-color : rgb( 45, 45, 45); ;\n"
"border-bottom: 0px;\n"
"border-top: 0px;\n"
"border-left: 0px;\n"
"border-right: 3px  solid rgb( 174, 243, 231 );\n"
"padding-right: 12px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"                            width:                  0px;\n"
"                            height:                 0px;\n"
"                            border-radius:          0px;\n"
" }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/social/email-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendsms.setIcon(icon3)
        self.sendsms.setIconSize(QtCore.QSize(20, 20))
        self.sendsms.setObjectName("sendsms")
        self.verticalLayout_5.addWidget(self.sendsms)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.gridLayout_4.addWidget(self.verticalFrame_panal, 0, 2, 1, 1)
        self.LESPAGES = QtWidgets.QStackedWidget(self.widget_main)
        self.LESPAGES.setStyleSheet("QScrollArea{\n"
"border : none;\n"
"}\n"
"QWidget{\n"
"background-color : rgb(45 ,45 ,45 );\n"
"font: 10pt \"Segoe UI\";\n"    #users data
"color : #858585;\n"
"\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: transparent;\n"
"    background: transparent;\n"
"    height: 10px;\n"
"    margin: 0px 21px 0 21px;\n"
"      border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #2f3939;;\n"
"    min-width: 25px;\n"
"     border-radius: 5px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: transparent;\n"
"}\n"
" QScrollBar:vertical {\n"
"       border: none;\n"
"    background: transparent;\n"
"    width: 10px;\n"
"    margin: 21px 0 21px 0;\n"
"       border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical { \n"
"       background: #2f3939;;\n"
"        min-height: 25px;\n"
"       border-radius: 5px;\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: transparent;\n"
"     height: 20px;\n"
"       border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"       border: none;\n"
"    background: transparent;\n"
"     height: 20px;\n"
"       border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox{\n"
"\n"
"font: 10pt \"Segoe UI\";\n"
"color : white;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton{ \n"
"background-color: rgba(35, 35, 35 , 60 ) ;\n"
"border-radius: 5px;\n"
"color : #858585 ;\n"
"border: 3px solid rgb(35, 35, 35);\n"
"\n"
"font: 12pt \"Segoe UI\";\n"
" }\n"
"QPushButton:hover{\n"
"border: 3px solid #858585;\n"
"}\n"
"\n"
"\n"
"QPushButton:checked{\n"
"background-color: rgb(34, 34, 34 ) ;\n"
"color : white ; \n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QSpinBox {\n"
"   padding-right: 1px; /* make room for the arrows */\n"
"    font: 12pt \"Segoe UI\";\n"
"color : white ;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"    width: 25px; /* 16 + 2*1px border-width = 15px padding + 3px parent border */\n"
"    border-width: 0px;\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-arrow {\n"
" image: url(\":/image/UpArrow_white.png\");\n"
"    width: 20px;\n"
"    height: 20px;\n"
"  \n"
"}\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right; /* position at bottom right corner */\n"
"    width: 25px;\n"
"    border-width: 1px;\n"
"    border-top-width: 0;\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-arrow {\n"
" image: url(\":/image/DownArrow_white.png\");\n"
"    width: 20px;\n"
"    height: 20px;\n"
" \n"
"}\n"
"      \n"
"\n"
"QHeaderView::section {\n"
"    background-color: #858585;\n"
"    padding: 4px;\n"
"    border: 1px solid rgb(45,45,45);\n"
"    font: 10.5pt \"Segoe UI\";\n"     #dont know
"    color : white ;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: rgb(45,45,45);\n"
"    font-size: 12pt;\n"
"     background-color:  rgb(35,35,35);\n"
"     border: 1px solid rgb(45,45,45);\n"
"    color : white\n"
"   \n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color:  rgb(35,35,35);\n"
"    border: 1px solid rgb(45,45,45);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.LESPAGES.setObjectName("LESPAGES")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page1)
        self.gridLayout_2.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        self.general = QtWidgets.QWidget(self.page1)
        self.general.setMinimumSize(QtCore.QSize(400, 0))
        self.general.setStyleSheet("QWidget{\n"
"background-color : rgb(35,35,35)  ;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"background-color: #ffffff ;\n"   #0A1414
"border-radius: 0px;\n"
"color : black ;\n"    #858585
"border: 1px solid #2f3939;\n"   #
"padding-right: 12px;\n"
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"font: 14pt \"Segoe UI\" yellow;\n" #10pt
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid black ;\n" #858585
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid  #858585;\n"     #858585
"    color : black ;\n"    #white
"}\n"
"\n"
"\n"
"QPushButton{ \n"
"background-color: #2f3939 ;\n"
"border-radius: 0px;\n"
"color : white ;\n" #white
"border: none;\n"
"    font: 10pt \"Segoe UI\";\n"
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"padding-right : 27px ;\n"
"padding-left : 27px ;\n"
" }\n"
"QPushButton:hover{\n"
"border: 1px solid white;\n"
"padding : 4px ;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.general.setObjectName("general")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.general)
        self.verticalLayout_8.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_8.setSpacing(20)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_name = QtWidgets.QLineEdit(self.general)
        self.line_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_name.setObjectName("line_name")
        self.horizontalLayout.addWidget(self.line_name)
        self.icon_name = QtWidgets.QPushButton(self.general)
        self.icon_name.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
"padding : 0px ;\n"
"}")
        self.icon_name.setText("")
        self.icon_name.setIcon(icon2)
        self.icon_name.setIconSize(QtCore.QSize(30, 30))
        self.icon_name.setObjectName("icon_name")
        self.horizontalLayout.addWidget(self.icon_name)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_phone = QtWidgets.QLineEdit(self.general)
        self.line_phone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_phone.setObjectName("line_phone")
        self.horizontalLayout_3.addWidget(self.line_phone)
        self.icon_phone = QtWidgets.QPushButton(self.general)
        self.icon_phone.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
"padding : 0px ;\n"
"}")
        self.icon_phone.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/technology/mobile-phone-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_phone.setIcon(icon4)
        self.icon_phone.setIconSize(QtCore.QSize(30, 30))
        self.icon_phone.setObjectName("icon_phone")
        self.horizontalLayout_3.addWidget(self.icon_phone)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line_carcompany = QtWidgets.QLineEdit(self.general)
        self.line_carcompany.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_carcompany.setObjectName("line_carcompany")
        self.horizontalLayout_4.addWidget(self.line_carcompany)
        self.icon_company = QtWidgets.QPushButton(self.general)
        self.icon_company.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
"padding : 0px ;\n"
"}")
        self.icon_company.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/commerce/bank-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_company.setIcon(icon5)
        self.icon_company.setIconSize(QtCore.QSize(30, 30))
        self.icon_company.setObjectName("icon_company")
        self.horizontalLayout_4.addWidget(self.icon_company)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line_carmodel = QtWidgets.QLineEdit(self.general)
        self.line_carmodel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_carmodel.setObjectName("line_carmodel")
        self.horizontalLayout_5.addWidget(self.line_carmodel)
        self.icon_model = QtWidgets.QPushButton(self.general)
        self.icon_model.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
"padding : 0px ;\n"
"}")
        self.icon_model.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/image/essential/key-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_model.setIcon(icon6)
        self.icon_model.setIconSize(QtCore.QSize(30, 30))
        self.icon_model.setObjectName("icon_model")
        self.horizontalLayout_5.addWidget(self.icon_model)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_carcode = QtWidgets.QLineEdit(self.general)
        self.line_carcode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_carcode.setObjectName("line_carcode")
        self.horizontalLayout_6.addWidget(self.line_carcode)
        self.icon_code = QtWidgets.QPushButton(self.general)
        self.icon_code.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
"padding : 0px ;\n"
"}")
        self.icon_code.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/image/technology/bar-code-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_code.setIcon(icon7)
        self.icon_code.setIconSize(QtCore.QSize(30, 30))
        self.icon_code.setObjectName("icon_code")
        self.horizontalLayout_6.addWidget(self.icon_code)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_notes = QtWidgets.QLineEdit(self.general)
        self.line_notes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_notes.setObjectName("line_notes")
        self.horizontalLayout_7.addWidget(self.line_notes)
        self.icon_notes = QtWidgets.QPushButton(self.general)
        self.icon_notes.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
"padding : 0px ;\n"
"}")
        self.icon_notes.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/image/essential/note-edit-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_notes.setIcon(icon8)
        self.icon_notes.setIconSize(QtCore.QSize(30, 30))
        self.icon_notes.setObjectName("icon_notes")
        self.horizontalLayout_7.addWidget(self.icon_notes)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.button_addcostumer = QtWidgets.QPushButton(self.general)
        self.button_addcostumer.setObjectName("button_addcostumer")
        self.verticalLayout_8.addWidget(self.button_addcostumer)
        self.gridLayout_2.addWidget(self.general, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 0, 1, 1)
        self.LESPAGES.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget = QtWidgets.QWidget(self.page2)
        self.horizontalWidget.setStyleSheet("QWidget{\n"
"background-color : rgb(35,35,35)  ;\n"
"border-radius: 5px;\n"
"}")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_search = QtWidgets.QLineEdit(self.horizontalWidget)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(200, 37))
        self.lineEdit_search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_search.setStyleSheet("QLineEdit {\n"
"background-color: #0A1414 ;\n"
"border-radius: 0px;\n"
"color : #858585 ;\n"
"border: 1px solid #2f3939;\n"
"padding-right: 12px;\n"
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"font: 10pt \"Segoe UI\";\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid #858585 ;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid  #858585;\n"
"    color : white ;\n"
"}\n"
"")
        self.lineEdit_search.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout_2.addWidget(self.lineEdit_search)
        self.searchcombobox = QtWidgets.QComboBox(self.horizontalWidget)
        self.searchcombobox.setMinimumSize(QtCore.QSize(200, 37))
        self.searchcombobox.setStyleSheet("QComboBox {\n"
"border-radius: 0px;\n"
"color :white  ;\n"
"border: 0px solid #2f3939;\n"
"padding-left: 22px;\n"
"padding-right: 12px;\n"
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"font: 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"background-color : #2f3939  ;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color : #2f3939  ;\n"
"}\n"
"\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"   \n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"      subcontrol-origin: padding;\n"
"    subcontrol-position: top left;\n"
"    border-left-width: 0px;\n"
"    border-left-style: solid; /* just a single line */\n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/image/DownArrow_white.png);\n"
"     width: 16px; \n"
"     height: 16px;\n"
"    padding-left : 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { \n"
"  \n"
"}\n"
"QComboBox:hover {\n"
"    \n"
"}")
        self.searchcombobox.setObjectName("searchcombobox")
        self.searchcombobox.addItem("")
        self.searchcombobox.addItem("")
        self.searchcombobox.addItem("")
        self.horizontalLayout_2.addWidget(self.searchcombobox)
        self.icon_search = QtWidgets.QPushButton(self.horizontalWidget)
        self.icon_search.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
"padding : 0px ;\n"
"}")
        self.icon_search.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/image/core/search-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_search.setIcon(icon9)
        self.icon_search.setIconSize(QtCore.QSize(30, 30))
        self.icon_search.setObjectName("icon_search")
        self.horizontalLayout_2.addWidget(self.icon_search)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.filtersort = QtWidgets.QComboBox(self.horizontalWidget)
        self.filtersort.setMinimumSize(QtCore.QSize(200, 37))
        self.filtersort.setStyleSheet("QComboBox {\n"
"border-radius: 0px;\n"
"color :white  ;\n"
"border: 0px solid #2f3939;\n"
"padding-left: 22px;\n"
"padding-right: 12px;\n"
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"font: 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"background-color : #2f3939  ;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color : #2f3939  ;\n"
"}\n"
"\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"   \n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"      subcontrol-origin: padding;\n"
"    subcontrol-position: top left;\n"
"    border-left-width: 0px;\n"
"    border-left-style: solid; /* just a single line */\n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/image/DownArrow_white.png);\n"
"     width: 16px; \n"
"     height: 16px;\n"
"    padding-left : 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { \n"
"  \n"
"}\n"
"QComboBox:hover {\n"
"    \n"
"}")
        self.filtersort.setObjectName("filtersort")
        self.filtersort.addItem("")
        self.filtersort.addItem("")
        self.filtersort.addItem("")
        self.filtersort.addItem("")
        self.horizontalLayout_2.addWidget(self.filtersort)
        self.icon_filter = QtWidgets.QPushButton(self.horizontalWidget)
        self.icon_filter.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
"padding : 0px ;\n"
"}")
        self.icon_filter.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/image/core/filter-grid-circle-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_filter.setIcon(icon10)
        self.icon_filter.setIconSize(QtCore.QSize(30, 30))
        self.icon_filter.setObjectName("icon_filter")
        self.horizontalLayout_2.addWidget(self.icon_filter)
        self.verticalLayout.addWidget(self.horizontalWidget)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.scrollArea = QtWidgets.QScrollArea(self.page2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 716, 653))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 6, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.gridLayout_8.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.LESPAGES.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setStyleSheet("QLineEdit {\n"
"background-color: #0A1414 ;\n"
"border-radius: 0px;\n"
"color : #858585 ;\n"
"border: 1px solid #2f3939;\n"
"padding-left: 12px;\n"
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"font: 10pt \"Segoe UI\";\n"   #dont know
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid #858585 ;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid  #858585 ;\n"
"    color : white ;\n"
"}")
        self.page3.setObjectName("page3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalWidget_2 = QtWidgets.QWidget(self.page3)
        self.horizontalWidget_2.setStyleSheet("QWidget{\n"
"background-color : rgb(35,35,35)  ;\n"
"border-radius: 5px;\n"
"}")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_search_2 = QtWidgets.QLineEdit(self.horizontalWidget_2)
        self.lineEdit_search_2.setMinimumSize(QtCore.QSize(200, 37))
        self.lineEdit_search_2.setStyleSheet("QLineEdit {\n"
"background-color: #0A1414 ;\n"
"border-radius: 0px;\n"
"color : #858585 ;\n"
"border: 1px solid #2f3939;\n"
"padding-right: 12px;\n"
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"font: 12pt \"Segoe UI\";\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid #858585 ;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid  #858585;\n"
"    color : white ;\n"
"}\n"
"")
        self.lineEdit_search_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_search_2.setPlaceholderText("")
        self.lineEdit_search_2.setObjectName("lineEdit_search_2")
        self.horizontalLayout_8.addWidget(self.lineEdit_search_2)
        self.searchcombobox_2 = QtWidgets.QComboBox(self.horizontalWidget_2)
        self.searchcombobox_2.setMinimumSize(QtCore.QSize(200, 37))
        self.searchcombobox_2.setStyleSheet("QComboBox {\n"
"border-radius: 0px;\n"
"color :white  ;\n"
"border: 0px solid #2f3939;\n"
"padding-left: 22px;\n"
"padding-right: 12px;\n"
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"font: 8pt \"Segoe UI\";\n"   #search font
"}\n"
"\n"
"QComboBox:editable {\n"
"background-color : #2f3939  ;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color : #2f3939  ;\n"
"}\n"
"\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"   \n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"      subcontrol-origin: padding;\n"
"    subcontrol-position: top left;\n"
"    border-left-width: 0px;\n"
"    border-left-style: solid; /* just a single line */\n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/image/DownArrow_white.png);\n"
"     width: 16px; \n"
"     height: 16px;\n"
"    padding-left : 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { \n"
"  \n"
"}\n"
"QComboBox:hover {\n"
"    \n"
"}")
        self.searchcombobox_2.setObjectName("searchcombobox_2")
        self.searchcombobox_2.addItem("")
        self.searchcombobox_2.addItem("")
        self.searchcombobox_2.addItem("")
        self.horizontalLayout_8.addWidget(self.searchcombobox_2)
        self.icon_search_2 = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.icon_search_2.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
"padding : 0px ;\n"
"}")
        self.icon_search_2.setText("")
        self.icon_search_2.setIcon(icon9)
        self.icon_search_2.setIconSize(QtCore.QSize(30, 30))
        self.icon_search_2.setObjectName("icon_search_2")
        self.horizontalLayout_8.addWidget(self.icon_search_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.filtersort_2 = QtWidgets.QComboBox(self.horizontalWidget_2)
        self.filtersort_2.setMinimumSize(QtCore.QSize(200, 37))
        self.filtersort_2.setStyleSheet("QComboBox {\n"
"border-radius: 0px;\n"
"color :white  ;\n"
"border: 0px solid #2f3939;\n"
"padding-left: 22px;\n"
"padding-right: 12px;\n"
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"font: 8pt \"Segoe UI\";\n" #name a-z
"}\n"
"\n"
"QComboBox:editable {\n"
"background-color : #2f3939  ;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color : #2f3939  ;\n"
"}\n"
"\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"   \n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"      subcontrol-origin: padding;\n"
"    subcontrol-position: top left;\n"
"    border-left-width: 0px;\n"
"    border-left-style: solid; /* just a single line */\n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/image/DownArrow_white.png);\n"
"     width: 16px; \n"
"     height: 16px;\n"
"    padding-left : 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { \n"
"  \n"
"}\n"
"QComboBox:hover {\n"
"    \n"
"}")
        self.filtersort_2.setObjectName("filtersort_2")
        self.filtersort_2.addItem("")
        self.filtersort_2.addItem("")
        self.filtersort_2.addItem("")
        self.filtersort_2.addItem("")
        self.horizontalLayout_8.addWidget(self.filtersort_2)
        self.icon_filter_2 = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.icon_filter_2.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
"padding : 0px ;\n"
"}")
        self.icon_filter_2.setText("")
        self.icon_filter_2.setIcon(icon10)
        self.icon_filter_2.setIconSize(QtCore.QSize(30, 30))
        self.icon_filter_2.setObjectName("icon_filter_2")
        self.horizontalLayout_8.addWidget(self.icon_filter_2)
        self.verticalLayout_3.addWidget(self.horizontalWidget_2)
        self.horizontalWidget1 = QtWidgets.QWidget(self.page3)
        self.horizontalWidget1.setStyleSheet("QWidget{\n"
"background-color : rgb(35,35,35)  ;\n"
"border-radius: 5px;\n"
"}")
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_9.setContentsMargins(9, 9, 49, 9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_message = QtWidgets.QLineEdit(self.horizontalWidget1)
        self.lineEdit_message.setMinimumSize(QtCore.QSize(200, 37))
        self.lineEdit_message.setStyleSheet("QLineEdit {\n"
"background-color: #0A1414 ;\n"
"border-radius: 0px;\n"
"color : #858585 ;\n"
"border: 1px solid #2f3939;\n"
"padding-right: 12px;\n"
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"font: 8pt \"Segoe UI\";\n"    #enter the sms
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid #858585 ;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid  #858585;\n"
"    color : white ;\n"
"}\n"
"")
        self.lineEdit_message.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_message.setObjectName("lineEdit_message")
        self.horizontalLayout_9.addWidget(self.lineEdit_message)
        self.icon_message = QtWidgets.QPushButton(self.horizontalWidget1)
        self.icon_message.setStyleSheet("QPushButton{ \n"
"background-color : none;\n"
"border:none;\n"
"padding : 0px ;\n"
"}")
        self.icon_message.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/image/social/chat-bubble-outline-badged.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_message.setIcon(icon11)
        self.icon_message.setIconSize(QtCore.QSize(30, 30))
        self.icon_message.setObjectName("icon_message")
        self.horizontalLayout_9.addWidget(self.icon_message)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.sendmessagebutton = QtWidgets.QPushButton(self.horizontalWidget1)
        self.sendmessagebutton.setMinimumSize(QtCore.QSize(200, 37))
        self.sendmessagebutton.setStyleSheet("\n"
"QPushButton{ \n"
"background-color: #2f3939 ;\n"
"border-radius: 0px;\n"
"color : white ;\n"
"border: none;\n"
"    font: 8pt \"Segoe UI\";\n"   #send sms button
"padding-top : 7px ;\n"
"padding-bottom : 7px ;\n"
"padding-right : 27px ;\n"
"padding-left : 27px ;\n"
" }\n"
"QPushButton:hover{\n"
"border: 1px solid white;\n"
"padding : 4px ;\n"
"}\n"
"\n"
"")
        self.sendmessagebutton.setObjectName("sendmessagebutton")
        self.horizontalLayout_9.addWidget(self.sendmessagebutton)
        self.verticalLayout_3.addWidget(self.horizontalWidget1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.select_all = QtWidgets.QCheckBox(self.page3)
        self.select_all.setStyleSheet("color : #858585;")
        self.select_all.setObjectName("select_all")
        self.horizontalLayout_10.addWidget(self.select_all)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.costumersselected = QtWidgets.QLabel(self.page3)
        self.costumersselected.setStyleSheet("font-size : 14px ; ")
        self.costumersselected.setObjectName("costumersselected")
        self.horizontalLayout_10.addWidget(self.costumersselected)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem11)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 716, 563))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 6, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.LESPAGES.addWidget(self.page3)
        self.gridLayout_4.addWidget(self.LESPAGES, 0, 1, 1, 1)
        self.THEAPPLICATIONCHILD.addLayout(self.gridLayout_4)
        self.gridLayout.addWidget(self.widget_main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.LESPAGES.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Garage Manger"))
        self.adduser.setText(_translate("MainWindow", "Add users      "))
        self.users.setText(_translate("MainWindow", "Users      "))
        self.sendsms.setText(_translate("MainWindow", "Send SMS to users      "))
        self.line_name.setPlaceholderText(_translate("MainWindow", " שם לקוח"))
        self.line_phone.setPlaceholderText(_translate("MainWindow", "מספר טלפון"))
        self.line_carcompany.setPlaceholderText(_translate("MainWindow", "חברת רכב"))
        self.line_carmodel.setPlaceholderText(_translate("MainWindow", "דגם"))
        self.line_carcode.setPlaceholderText(_translate("MainWindow", "קוד רכב"))
        self.line_notes.setPlaceholderText(_translate("MainWindow", "הערות"))
        self.button_addcostumer.setText(_translate("MainWindow", "Add costumer"))
        self.searchcombobox.setItemText(0, _translate("MainWindow", "Search by name "))
        self.searchcombobox.setItemText(1, _translate("MainWindow", "Search by car company "))
        self.searchcombobox.setItemText(2, _translate("MainWindow", "Search by car model "))
        self.filtersort.setItemText(0, _translate("MainWindow", "Name (a -z)"))
        self.filtersort.setItemText(1, _translate("MainWindow", "Name (z-a)"))
        self.filtersort.setItemText(2, _translate("MainWindow", "Date (Earliest)"))
        self.filtersort.setItemText(3, _translate("MainWindow", "Date (Lastest)"))
        self.searchcombobox_2.setItemText(0, _translate("MainWindow", "Search by name "))
        self.searchcombobox_2.setItemText(1, _translate("MainWindow", "Search by car company "))
        self.searchcombobox_2.setItemText(2, _translate("MainWindow", "Search by car model "))
        self.filtersort_2.setItemText(0, _translate("MainWindow", "Name (a -z)"))
        self.filtersort_2.setItemText(1, _translate("MainWindow", "Name (z-a)"))
        self.filtersort_2.setItemText(2, _translate("MainWindow", "Date (Earliest)"))
        self.filtersort_2.setItemText(3, _translate("MainWindow", "Date (Lastest)"))
        self.lineEdit_message.setPlaceholderText(_translate("MainWindow", "Entre the SMS here .. "))
        self.sendmessagebutton.setText(_translate("MainWindow", "Send SMS"))
        self.select_all.setText(_translate("MainWindow", "Select all"))
        self.costumersselected.setText(_translate("MainWindow", "0 Costumers selected "))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
